controller_names:
   - arm_controller
   - finger_controller

arm_controller:
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
    - arm0_shoulder_yaw
    - arm0_shoulder_pitch
    - arm0_elbow_pitch
    - arm0_elbow_roll
    - arm0_wrist_pitch
    - arm0_wrist_roll

finger_controller:
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - arm0_fingers
